### ISSUE TITLE
empty reply from server

### ISSUE THREAD

**Issue by bwearp** [harblaith7/k8s-app#9]
Hello,

Loving the course. Thanks very much. I'm having an issue connecting to the server on port 3005

**server-srv.yml:**

```
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005
```

When I try to connect using a browser or curl it gives me an empty reply from server. So I cannot post the route in postman...

**kubectl logs server-pod:**
```
> server@1.0.0 start
> node ./src/index.js

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo-srv
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:846:32)
    at /app/node_modules/mongoose/lib/index.js:350:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1154:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:349:20)
    at main (/app/src/index.js:34:24)
    at Object.<anonymous> (/app/src/index.js:49:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'mongo-srv:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
Listening on port 3000!!
```

Many thanks for your help### ###

**Comment by mohemos** [comment]
This issue occurred because you probably used a different metadata name for your mongoDB service instead of `mongo-srv`
